###Crear usuario ###
POST http://localhost:5000/Usuarios/CrearUsuario
Content-Type: application/json

{
    "nombre":"Test3",
    "apellido1":"test3",
    "apellido2":"test3",
    "cargo":"test3",
    "municipalidad":"test3",
    "correo":"test3",
    "contrasena":"test3",
    "num_tel":"test3",
    "id_rol": 1
}

### LOGIN DE USUARIO
POST http://localhost:5000/Usuarios/login
Content-Type: application/json

{
  "correo": "test3",
  "contrasena": "test3"
}

###Obtener todos los usuarios ###
GET http://localhost:5000/Usuarios/ObtenerUsuarios

### Obtener Usuario por Id
GET http://localhost:5000/Usuarios/1
Content-Type: application/json

### Actualizar usuario
PUT http://localhost:5000/Usuarios/EditarUsuario/1
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido1": "Pérez",
    "apellido2": "Gómez",
    "cargo": "Administrador",
    "municipalidad": "San José",
    "correo": "juan.nuevo@example.com",
    "contrasena": "nuevaContrasena123",
    "num_tel": "88887777",
    "id_rol": 1
}

### Eliminar usuario
DELETE http://localhost:5000/Usuarios/EliminarUsuario/2